version: "3"

services:
  api-gateway:
    build:
      context: services/gateway
    ports:
      - 8080:5555
    command: "python wsgi.py"

  auth:
    build:
      context: services/auth
    command: "python wsgi.py"

  scrapper:
    build:
      context: services/scrapper
    command: "python wsgi.py"