version: "3"

services:

  gateway:
    build:
      context: services/gateway
    ports:
      - 5555
    command: "gunicorn wsgi:app --worker-tmp-dir /dev/shm --bind 0.0.0.0:5555"

  auth:
    build:
      context: services/auth
    command: "python wsgi.py"

  scrapper:
    build:
      context: services/scrapper
    command: "python wsgi.py"

  reverse-proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - gateway