version: "3"

services:
  api-gateway:
    build:
      context: gateway
    ports:
      - 8080:5555
    command: "python wsgi.py"

  auth:
    build:
      context: auth
    command: "python wsgi.py"

  scrapper:
    build:
      context: scrapper
    command: "python wsgi.py"